import type { City } from "../astro/types.js";
import raw from "./cities.json" with { type: "json" };

// Curated destination/ranking dataset (docs/DECISIONS.md, approved
// 2026-09-03). Generated by scripts/import-cities.ts from GeoNames data
// (CC BY 4.0, attribution required -- see data/raw/geonames/SOURCES.md).
// Do not hand-edit cities.json; re-run the import script instead.
export const CITIES: readonly City[] = raw as City[];

export function getCityById(id: string): City | undefined {
  return CITIES.find((c) => c.id === id);
}
